---
title: How to mentor at a Code Club
hero_image: images/X C.png
description: Learn about the different roles in a Code Club club, mentoring styles and approaches as well as the resources available to support mentors.
version: 1
listed: false
copyedit: true
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Roles and time commitment
- title: Skills and group management
- title: Mentoring styles
- title: Supporting all learners 
- title: Reflection quiz
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Learning resources
- title: Common programming languages
- title: Celebrate and showcase
- title: Resources for mentors
- title: Reflection quiz
  knowledge_quiz:
    path: quiz2
    version: 1
    questions: 3
    passing_score: 3
  completion:
    - external
- title: What next?
